FAQ_list = [
    "How old are you?", 
    "Where do you live?", 
    "What is your name?",
    "What is the criteria for EB1 visa?",
    "What is the purpose of Form I-130?",
    "How does an F-1 student maintain their status?",
    "What are some common cultural misunderstandings experienced by international students?",
    "What is the H-1B cap?",
    "What are the eligibility criteria for EB-1 extraordinary ability?",
    "What are the requirements for an O-1 visa in the arts?",
    "What business structures are best for immigrant entrepreneurs?",
    "What travel documents are needed for a green card holder?",
    "How long is STEM OPT extension valid for?",
    "What is the process for adjusting status to a green card?",
    "What is the function of Form I-485?",
    "How can an F-1 student obtain work authorization?",
    "What resources are available to help international students adjust to US culture?",
    "What is the prevailing wage for H-1B positions?",
    "What is the National Interest Waiver (NIW)?",
    "Can an O-1 holder bring dependents to the US?",
    "What funding options are available for immigrant-owned businesses?",
    "Can a green card holder travel to Cuba?",
    "What are the reporting requirements for OPT?",
    "What are the different categories of green cards?",
    "What is the purpose of Form I-765?",
    "What are the restrictions on F-1 student employment?",
    "How does homesickness affect international students?",
    "What is the H-1B lottery?",
    "What is the difference between EB-2 and EB-3?",
    "How does the O-1 visa differ from the H-1B visa?",
    "What are some legal considerations for immigrant entrepreneurs?",
    "What are the consequences of abandoning permanent resident status?",
    "What is the unemployment rule for OPT?",
    "How can a family member sponsor a green card?",
    "What is a Request for Evidence (RFE)?",
    "Can an F-1 student start a business?",
    "How do international students navigate US social customs?",
    "What are the requirements for H-1B portability?",
    "What is the PERM labor certification process?",
    "Can an O-1 visa be extended?",
    "What are incubators and accelerators for immigrant startups?",
    "What are the rules for re-entry permits for green card holders?",
    "What is the 24-month bar for STEM OPT?",
    "What is the Diversity Visa Lottery?",
    "What is a Notice of Action (NOA)?",
    "What is Curricular Practical Training (CPT)?",
    "How do international students manage culture shock related to food?",
    "What are the requirements for an H-1B transfer?",
    "What are the advantages of the EB-1 category?",
    "What are the criteria for O-1 visa in business?",
    "How can immigrants access small business loans?",
    "What are the implications of having a criminal record on international travel as a green card holder?",
    "What is the role of the DSO in OPT?",
    "What are the grounds for green card revocation?",
]
